before_script:
  - bundle install --path=/home/gitlab-runner/builds/shared/${CI_PROJECT_NAME}/gems
  - cp config/database.example.yml config/database.yml
  - cp config/env.example.yml config/env.yml

production:
  only:
    - master
  script:
    - bundle exec cap production deploy
  when: manual

staging:
  stage: deploy
  only:
    - develop
  script:
    - bundle exec cap staging deploy
