version: '3'
services:
  db:
    container_name: evally_recruitable_db
    image: postgres:10.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    environment:
      - RAILS_ENV=development
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: evally_recruitable
    command: bin/rails s -p 3030 -b '0.0.0.0'
    user: ${CURRENT_USER}
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/env.yml:/app/config/env.yml
    ports:
      - '3030:3030'
    depends_on:
      - db

volumes:
  postgres:

networks:
  default:
    external:
      name: evally_network

# docker network create evally_network --subnet 172.24.24.0/24
# CURRENT_USER=$(id -u):$(id -g) add to .bashrc / .zshrc to run container as non-root user
