version: '3'
services:
  db:
    container_name: evally_recruitable_db
    image: postgres:10.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    env_file:
      - ./docker/docker.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: evally_recruitable
    command: bin/rails s -p 3030 -b '0.0.0.0'
    user: ${CURRENT_USER}
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
    ports:
      - '3030:3030'
    depends_on:
      - db

volumes:
  postgres:

# CURRENT_USER=$(id -u):$(id -g) add to .bashrc / .zshrc to run container as non-root user
